### ISSUE TITLE
not responding after starting a conversion and a false Failure at the end of the conversion

### ISSUE THREAD

**Issue by Tolozen** [rimerosolutions/entrusted#7]
For every conversion I do, a cmd window opens (I believe to start the Docker container) and does not close, and the entrusted-gui begins Not Responding. I can then just close the cmd window and it opens a new one and continues with the page separation. At the end of the conversion, it says it has Failed and the Logs end with "Access is denied. (os error 5)." Even with this supposed failure, the PDF does come out the other end successfully. 

I'm on Windows 10, using Docker (which I'm not very familiar with). I would like to say I appreciate entrusted because it handles very large PDFs and dangerzone does not seem to.

**Comment by yveszoundi** [comment]
@Tolozen, thanks for trying out the application and reporting the issue. 
Windows testing is poor as I don't have a personal Windows machine.

Can you please test a "snapshot build" of the desktop interface (link below) and let me know if the issue is resolved?
https://github.com/yveszoundi/entrusted-snapshots/releases/download/20220730/entrusted-gui-20220730.exe

If it works fine for you, then I'll release a new version next week.

**Comment by Tolozen** [comment]
Do I need a new Docker image or something? It seems now that the Docker command doesn't even run. No cmd window opens, no not responding, but it also just stops at 1% permanently. Thanks for the fast response time and I'm glad I can help with the Windows release.

**Comment by yveszoundi** [comment]
Thanks for helping, I created another build today that hopefully fixes it all: https://github.com/yveszoundi/entrusted-snapshots/releases/download/20220801/entrusted-gui-20220801.exe.

### About the main current issue
I had some incomplete changes that were setting wrong parameters (always assuming that full-text option is set). I'm hoping that it was the only issue, as there is no cmd window anymore.

### Drag and drop files as administrator

- This seems to be by design on Windows, per similar issue for the "new" Windows Terminal (https://github.com/microsoft/terminal/issues/7754). 
- Some people claim to be able to bypass that "annoyance" after fiddling with the Windows registry, but I would not recommend that personally: https://answers.microsoft.com/en-us/windows/forum/all/how-to-fix-drag-and-drop-in-windows-10/0ea16377-dfcf-4a28-9e38-c35f4113202b?page=14. Maybe just turning off Windows UAC also work too.

**Comment by Tolozen** [comment]
>  It seems now that the Docker command doesn't even run. No cmd window opens, no not responding, but it also just stops at 1% permanently.
Unfortunately this issue is still persisting for me. I could record a video if that could help somehow but there's not much to see. No logs are created either as I'm guessing not much is able to happen.

**Comment by yveszoundi** [comment]
I'll try to reproduce the issue tomorrow on a Windows 11 machine with Docker. Sadly I don't have access to any Windows 10 computers anymore but I'm hoping that the same is also happening on Windows 11.

A video recording probably wouldn't be useful. I suspect that the windows process either dies immediately or "entrusted" is unable to capture any log/output from Docker.

**Comment by yveszoundi** [comment]
I was able to reproduce everything that you described on Windows 11 (for both the 0.2.3 release and the preview builds that you tested). Please try the new build and hopefully it'll be a success this time around.

**New build**
https://github.com/yveszoundi/entrusted-snapshots/releases/download/20220802/entrusted-gui-20220802.exe

**Root cause of the problems**

- The "permission denied issues" upon successful conversion are due to failures while updating file modification dates (it doesn't appear to be required on Windows, so I'm now gracefully ignoring the error, *for now*..)
- The "conversion stuck at 1%" is a programming mistake that seems to only manifest itself on Windows. Because I was not "processing" the output of some sanity checks, the application didn't realize that it should actually start converting files...

**Comment by Tolozen** [comment]
Works great for me now. Don't even have to open it in administrator so I can drag files in, which makes things more convenient. Thanks for your work on this and I hope I could help you make the Windows release better.

**Comment by yveszoundi** [comment]
The fix for this issue has been released in `0.2.4` today. The first conversion takes longer as it needs to download a new Docker image (~600 MB), prior initiating the actual processing. 

Thanks again for your help and collaboration.
